### PR TITLE
Add win homepage

### PR DESCRIPTION
**Pull request by keithamus**
Adds win homepage to the win app. Come on all we have 4 minutes to make our deadline!

### CODE REVIEW

**Comment by keithamus** [comment]
It does fix that, as part of me getting this working, yes.

**Comment by sebinsua** [comment]
Looks reasonable to me - I'd happily merge.

**Comment by keithamus** [comment]
Proptypes file removed. Please feel free to merge.

**Comment by sebinsua** [comment]
Merged. :)

**Pull request merged**
